name: Build Application
on: push
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: check node version
        run: node --version
      - name: Checkout code from Github
        uses: actions/checkout@v3
      - name: Install Node Modules
        run: npm install